gmh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

urlpatterns = [
    path('', RedirectView.as_view(url='games/'), name='index'),
    path('games/', include('game.urls'), name='games'),
    path('mods/', include('mod.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mod/urls.py
from django.db import models
from django.urls import reverse, path
from .views import *

urlpatterns = [
    path('',             ModListView.as_view(),   name='mod-list'),
    path('detail/<pk>/', ModDetailView.as_view(), name='mod-detail'),
    path('create/',      ModCreateView.as_view(), name='mod-create'),
    path('detail/<pk>/download', download_mod_content, name='mod-download'),
]

mod/models.py
from typing import Iterable
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator, RegexValidator, FileExtensionValidator, MinValueValidator, MaxValueValidator
from django.core.files.base import ContentFile
from user.models import User
from game.models import Game
import re
from django.core.exceptions import ValidationError
import datetime
import zipfile
import io
from PIL import Image
import os
import uuid
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import *

class ModPath:
    def _sanitize_extentsion(ext: str):
        return re.sub('[^a-zA-Z0-9]', '', ext)

    def _sanitize_filename(filename: str):
        ext = None
        ext_len = 0
        sep = filename.rfind('.')
        if sep != -1:
            ext = filename[sep + 1:]
            ext = ModPath._sanitize_extentsion(ext)
            filename = filename[:sep]
        if ext is not None:
            ext_len = len(ext) + 1
        
        length = len(filename) + ext_len
        if length > 255:
            filename = filename[:255-ext_len]
        filename = re.sub('[^a-zA-Z0-9]', '-', filename)
        if ext is not None:
            filename += ('.' + ext)
        return filename

    def icon(instance, filename):
        return f'games/{instance.related_game.id}/icon.jpg'

    def image(instance, filename):
        game_id = instance.related_mod.related_game.id
        mod_pk  = instance.related_mod.pk
        return f'games/{game_id}/mods/{mod_pk}/images/{ModPath._sanitize_filename(filename)}'

    def content(instance, filename):
        game_id = instance.related_mod.related_game.id
        mod_pk  = instance.related_mod.pk
        return f'games/{game_id}/mods/{mod_pk}/files/{ModPath._sanitize_filename(filename)}'

class ModCategory(models.Model):
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

class Mod(models.Model):    
    title           = models.CharField(max_length=255, verbose_name='Nombre del mod')
    short_desc      = models.CharField(max_length=5000, verbose_name='Resumen del mod de unas pocas lineas', blank=True)
    desc            = models.CharField(max_length=5000, verbose_name='Descripcion')
    version         = models.IntegerField(validators=[MinValueValidator(1)], verbose_name='Version')
    author          = models.ForeignKey(User, on_delete=models.PROTECT)
    related_game    = models.ForeignKey(Game, on_delete=models.PROTECT, verbose_name='Juego base')
    icon            = ProcessedImageField(upload_to=ModPath.icon,
                                          processors=[Resize(340, 240)],
                                          format='JPEG',
                                          options={'quality': 100})
    data_size       = models.BigIntegerField()
    upload_date     = models.DateTimeField(auto_now_add=True)
    downloads_count = models.BigIntegerField(default=0)
    youtube_link    = models.URLField(null=True, blank=True)
    category        = models.ManyToManyField(ModCategory)
    ratings_sum     = models.IntegerField(verbose_name='Suma de todas las valoraciones (van de 1 a 5)', default=0)
    ratings_count   = models.IntegerField(verbose_name='Conteo de valoraciones unicas por usuario', default=0)

    def get_absolute_url(self):
        return reverse('mod-detail', args=[str(self.pk)])

    def get_some_categories(self):
        return self.category.values_list('name', flat=True)[:3]
    
    def calc_rating(self):
        self.ratings_sum / self.ratings_count

    def __str__(self):
        return self.title

class ModImage(models.Model):
    related_mod  = models.ForeignKey(Mod, on_delete=models.CASCADE)
    image        = ProcessedImageField(upload_to=ModPath.image,
                                       processors=[Resize(1280, 720)],
                                       format='JPEG',
                                       options={'quality': 100})
    
    def __str__(self):
        file_name = self.image.name.split('/')[-1]
        return f'Image [{file_name}]'

class ModFile(models.Model):
    related_mod        = models.ForeignKey(Mod, on_delete=models.CASCADE)
    file               = models.FileField(upload_to=ModPath.content)
    original_file_name = models.CharField(max_length=255)

mod/forms.py
from typing import Any, Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList
from .models import *
from user.models import *
import zipfile
import io

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = [single_file_clean(data, initial)]
        return result

class ModForm(forms.ModelForm):
    files = MultipleFileField()
    images = MultipleFileField()
    desc = forms.CharField(max_length=5000, widget=forms.Textarea)

    class Meta:
        model = Mod
        fields = (
            'related_game',
            'title',
            'short_desc',
            'version',
            'icon',
            'desc',
            'youtube_link',
            'category',
        )

mod/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Mod, ModImage, ModFile
from game.models import Game
from .forms import ModForm
import io
import zipfile
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, Http404
from django.core.files.base import ContentFile
from django.urls import reverse

class ModListView(ListView):
    model = Mod
    paginate_by = 4

class ModDetailView(DetailView):
    model = Mod

class ModCreateView(View):
    def get(self, request: HttpRequest, *args, **kargs):
        form = ModForm()

        if (request.GET.get('game') is not None):
            try:
                form = ModForm(initial={
                    'related_game': Game.objects.get(id=request.GET['game'])
                })
            except:
                pass

        return render(request, 'mod/mod_create.html', context={
            'form': form
        })
    
    def post(self, request: HttpRequest, *args, **kargs):
        form = ModForm(request.POST, request.FILES)
        
        if not form.is_valid():
            return render(request, 'mod/mod_create.html', context={
                'form': form
            })
        else:         
            instance = form.save(commit=False)
            instance.author = request.user

            total_size = 0
            for file in request.FILES.getlist('files'):
                total_size = total_size + file.size

            instance.data_size = total_size
            instance.save()

            for file in request.FILES.getlist('files'):
                ModFile.objects.create(related_mod=instance, file=file, original_file_name=file.name)
            
            for image in request.FILES.getlist('images'):
                ModImage.objects.create(related_mod=instance, image=image)        

            return redirect(reverse('mod-detail', args=[str(instance.pk)]))

def download_mod_content(request, pk):   
    mod = None
    try:
        mod = Mod.objects.get(pk=pk)
    except:
        return Http404()
    
    buf = io.BytesIO()
    zip_mem = zipfile.ZipFile(buf, 'w', zipfile.ZIP_STORED)
    files = ModFile.objects.filter(related_mod=mod)
    for file in files:
        zip_mem.writestr(file.original_file_name, file.file.read())
    zip_mem.close()    

    response = HttpResponse()
    response.status_code = 200
    response.content = buf.getvalue()
    response.headers = {
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': 'attachment; filename="modcontent.zip"'
    }

    return response

mod/templates/mod/mod_create.html
{% extends "base_generic.html" %}

{% block content %}

{% if form.errors %}
<p>Parece que hay algunos errores en tu formulario...</p>

{% for field in form %}
    <p>+ {{field.label}}:</p>
    {% for error in field.errors %}
        <span class="text-danger">{{error}}</span></p>
    {% endfor %}
{% endfor %}

{% else %}
<form method="post" action="#" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table">
        {{form.as_table}}
        <tr>
            <td colspan="2">
                <input type="submit" value="Crear">
            </td>
        </tr>
    </table>
</form>
{% endif %}

{% endblock %}

mod/templates/mod/mod_detail.html
{% extends "base_generic.html" %}
{% load extra_filters %}
{% load static %}

{% block content %}
<div class="bg-dark">
    <div class="p-3">
        <div class="row mb-3">
            <div class="col-4">
                <img src="{{ object.icon.url }}" class="w-100 border border-1 rounded-2" style="
                    border-color: grey !important;
                    aspect-ratio: 16/9;
                ">
            </div>
            <div class="col-8">
                <div class="d-flex">
                    <p class="mod-detail-title">{{ object.title }}</p>
                    <div class="d-flex align-items-center gap-2 ps-4" style="position: relative; top: .2rem;">
                        {% for categ in object.get_some_categories %}
                        <p class="mod-detail-category">{{categ|upper}}</p>
                        {% endfor %}
                    </div>
                </div>
                
                {% include "widgets/mod_ratings.html" %}

                <p class="mod-detail-label">Base game:&nbsp;
                    <a href="{% url 'game-mods-list' mod.related_game.pk %}">{{ mod.related_game.title }}</a>
                </p>
                <p class="mod-detail-label">Author:&nbsp;
                    <a href="#">{{ mod.author }}</a>
                </p>
                <p class="mod-detail-short-description">{{ object.short_desc }}</p>
                <div class="d-flex justify-content-between">
                    <p class="mod-detail-label">
                        Size:&nbsp;&nbsp;<span style="font-weight: bold;">{{ object.data_size|pretty_size }}</span>
                    </p>
                    <p class="mod-detail-label">
                        Downloads:&nbsp;&nbsp;<span style="font-weight: bold;">{{ object.downloads_count }}</span>
                    </p>
                </div>
            </div>
        </div>

        <hr>

        {% include "widgets/image_preview_modal.html" %}

        <script>
            function preview_image(a) {
                const modalDOM = document.getElementById('image-preview-modal');
                const img = modalDOM.querySelector('img');
                img.src = a.querySelector('img').src;
                const modal = bootstrap.Modal.getOrCreateInstance(modalDOM);
                modal.show();
            }
        </script>

        <div class="row mb-3 mt-3">
            {% for image in object.modimage_set.all %}
            <div class="col-4">
                <a href="#" onclick="preview_image(this)">
                    <img src="{{ image.image.url }}" class="w-100" style="box-shadow: .2rem .2rem 0 #343434">
                </a>
            </div>
            {% endfor %}
        </div>
        
        <div class="row">
            <div class="col-8">
                <p class="mod-detail-description">{{ object.desc }}</p> 
            </div>
            <div class="col-4">
                <table class="table table-sm table-dark">
                    <tr>
                        <th>FILE</th>
                        <th>SIZE</th>
                    </tr>
                    {% for file in object.modfile_set.all %}
                    <tr>
                        <td>{{ file.original_file_name }}</td>
                        <td>{{ file.file.size|pretty_size }}</td>
                    </tr>
                    {% endfor %}
                </table>
                <a href="{% url 'mod-download' object.pk %}" class="btn btn-secondary w-100">
                    Download .ZIP
                </a>
            </div>
        </div>        
    </div>
</div>

{% endblock %}

mod/templates/mod/mod_list.html
{% extends "base_generic.html" %}

{% block content %}

<div class="row">
    {% for mod in page_obj %}
    <div class="col col-md-6 col-xl-4 col-xxl-3 mb-4">
        {% include "widgets/mod_card.html" %}
    </div>
    {% endfor %}
</div>

<style>
    .disable-links > a
    {
        color: lightgray;
        text-decoration: none;
    }
</style>

<div class="d-flex flex-row gap-3 justify-content-center align-items-center disable-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt&lt;</a>
    {% else %}
    <a href="#" class="invisible">&lt;&lt;&lt;</a>
    {% endif %}

    <a href="#">{{ page_obj.number }}/{{ page_obj.paginator.num_pages }}</a>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&gt;&gt;&gt;</a>
    {% else %}
    <a href="#" class="invisible">&gt;&gt;&gt;</a>
    {% endif %}
</div>

{% endblock %}